Add post-stratification tutorial page (mdx) (#142)
Summary:
Pull Request resolved: https://github.com/facebookresearch/balance/pull/142

This adds a documentation page that embeds the post-stratification tutorial notebook as HTML on the balance website.

This is split from the previous diff because the MDX file references a URL that the original diff cannot see, causing validation errors.

```
Error:  Unable to build website for locale en.
Error:  Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/docs/statistical_methods/poststratify/:
   -> linking to ../../tutorials/quickstart_poststratify/ (resolved as: /docs/docs/tutorials/quickstart_poststratify/)

    at throwError (/home/runner/work/balance/balance/website/node_modules/docusaurus/logger/lib/index.js:76:11)
    at handleBrokenLinks (/home/runner/work/balance/balance/website/node_modules/docusaurus/core/lib/server/brokenLinks.js:153:47)
    at async buildLocale (/home/runner/work/balance/balance/website/node_modules/docusaurus/core/lib/commands/build.js:186:5)
    at async tryToBuildLocale (/home/runner/work/balance/balance/website/node_modules/docusaurus/core/lib/commands/build.js:41:20)
    at async mapAsyncSequential (/home/runner/work/balance/balance/website/node_modules/docusaurus/utils/lib/jsUtils.js:34:24)
    at async Command.build (/home/runner/work/balance/balance/website/node_modules/docusaurus/core/lib/commands/build.js:76:21)
[INFO] Docusaurus version: 2.4.3
Node version: v18.20.8
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

NOTE: this can only be tested after the previous diff has landed.

Differential Revision: D86857631

fbshipit-source-id: 6b524cc89aa00b32508ec2e314a0a21ef0999fe7