Fixing failure of tests due to non-excat match
Summary:
Fixing two tests failing:
https://github.com/facebookresearch/balance/actions/runs/3728563562/jobs/6323684988

FAILED tests/test_cbps.py::Testcbps::test_gmm_function - AssertionError: 91665.75 != 91665.751 : Ellipsis
FAILED tests/test_cbps.py::Testcbps::test_gmm_loss - AssertionError: 91665.75 != 91665.751 : Ellipsis

We don't need the answer to be the same up to 3 digits, 2 are enough.

Reviewed By: talgalili

Differential Revision: D42136591

fbshipit-source-id: ca8078fbedfa1bd0c2dab41f738cb5df59e65a15